export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const REGISTRATION_START = 'REGISTRATION_START';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAIL = 'REGISTRATION_FAIL';
export const RESET_REGISTRATION_COMPLETED = 'RESET_REGISTRATION_COMPLETED';

export const BEGIN_FORM_ERROR_CHECKING = 'BEGIN_FORM_ERROR_CHECKING';
export const SET_FORM_ERROR_START = 'SET_FORM_ERROR_START';
export const SET_FORM_ERROR_END = 'SET_FORM_ERROR_END';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const FETCH_VIDEOS_START = 'FETCH_VIDEOS_START';
export const FETCH_VIDEOS_SUCCESS = 'FETCH_VIDEOS_SUCCESS';
export const FETCH_VIDEOS_FAIL = 'FETCH_VIDEOS_FAIL';

export const UPLOAD_VIDEO_START = 'UPLOAD_VIDEO_START';
export const UPLOAD_VIDEO_SUCCESS = 'UPLOAD_VIDEO_SUCCESS';
export const UPLOAD_VIDEO_FAIL = 'UPLOAD_VIDEO_FAIL';

export const DELETE_VIDEO_START = 'DELETE_VIDEO_START';
export const DELETE_VIDEO_SUCCESS = 'DELETE_VIDEO_SUCCESS';
export const DELETE_VIDEO_FAIL = 'DELETE_VIDEO_FAIL';

export const REQUEST_PROCESSING_START = 'REQUEST_PROCESSING_START';
export const REQUEST_PROCESSING_SUCCESS = 'REQUEST_PROCESSING_SUCCESS';
export const REQUEST_PROCESSING_FAIL = 'REQUEST_PROCESSING_FAIL';

export const FETCH_ALGORITHMS_START = 'FETCH_ALGORITHMS_START';
export const FETCH_ALGORITHMS_SUCCESS = 'FETCH_ALGORITHMS_SUCCESS';
export const FETCH_ALGORITHMS_FAIL = 'FETCH_ALGORITHMS_FAIL';

export const FETCH_RESULTS_START = 'FETCH_RESULTS_START';
export const FETCH_RESULTS_SUCCESS = 'FETCH_RESULTS_SUCCESS';
export const FETCH_RESULTS_FAIL = 'FETCH_RESULTS_FAIL';

export const POLL_STATUS_START = 'POLL_STATUS_START';
export const POLL_STATUS_SUCCESS = 'POLL_STATUS_SUCCESS';
export const POLL_STATUS_FAIL = 'POLL_STATUS_FAIL';

export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

export const SET_ACTIVE_PAGE = 'SET_ACTIVE_PAGE';
export const SET_SORT_KEY = 'SET_SORT_KEY';
export const SET_SORT_ORDER = 'SET_SORT_ORDER';
